import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { FaqCategory, JobPost, PublicCourseOption, PublicFaq, SiteSettings, SuccessStory } from "@/types/support";
type Row=Record<string,unknown>;
function fail(context:string,error:{message:string}):never{console.error(`[support.service] ${context}: ${error.message}`);throw new Error(context)}
export async function getPublishedSuccessStories(){const{data,error}=await createSupabaseServerClient().from("success_stories").select("*").eq("status","published").eq("consent_confirmed",true).or(`published_at.is.null,published_at.lte.${new Date().toISOString()}`).order("display_order");if(error)fail("Không thể tải thành quả học viên",error);return(data??[])as SuccessStory[]}
export async function getActiveFaqs(){const db=createSupabaseServerClient();const[{data:categories,error:ce},{data:faqs,error:fe}]=await Promise.all([db.from("faq_categories").select("*").eq("is_active",true).order("display_order"),db.from("faqs").select("*").eq("is_active",true).order("display_order")]);if(ce)fail("Không thể tải danh mục FAQ",ce);if(fe)fail("Không thể tải FAQ",fe);return{categories:(categories??[])as FaqCategory[],faqs:(faqs??[])as PublicFaq[]}}
export async function getPublishedJobs(){const{data,error}=await createSupabaseServerClient().from("job_posts").select("*").eq("status","published").or(`application_deadline.is.null,application_deadline.gte.${new Date().toISOString().slice(0,10)}`).order("display_order");if(error)fail("Không thể tải tuyển dụng",error);return(data??[])as JobPost[]}
export async function getJobBySlug(slug:string){const jobs=await getPublishedJobs();return jobs.find(j=>j.slug===slug)??null}
export async function getPublicSiteSettings():Promise<SiteSettings>{const{data,error}=await createSupabaseServerClient().from("site_settings").select("setting_key,setting_value").eq("is_public",true);if(error)fail("Không thể tải thông tin website",error);const rows=(data??[])as Row[];return{organization:(rows.find(r=>r.setting_key==="organization")?.setting_value??{})as Record<string,unknown>,contact:(rows.find(r=>r.setting_key==="contact")?.setting_value??{})as Record<string,unknown>}}
export async function getPublishedCourseOptions():Promise<PublicCourseOption[]>{const{data,error}=await createSupabaseServerClient().from("courses").select("id,title,slug").eq("status","published").order("display_order");if(error)fail("Không thể tải khóa học",error);return(data??[])as PublicCourseOption[]}
async function insert(table:string,input:Record<string,unknown>){const{error}=await createSupabaseServerClient().from(table).insert(input);if(error){console.error(`[support.service] ${table} insert failed`,{code:error.code});throw new Error("FORM_INSERT_FAILED")}}
export const createContactMessage=(input:Record<string,unknown>)=>insert("contact_messages",input);
export const createTrialRegistration=(input:Record<string,unknown>)=>insert("trial_registrations",input);
export const createCourseRegistration=(input:Record<string,unknown>)=>insert("course_registrations",input);
export const createJobApplication=(input:Record<string,unknown>)=>insert("job_applications",input);
