import Link from "next/link";

export type AdminColumn={key:string;label:string;format?:(value:unknown,row:Record<string,unknown>)=>React.ReactNode};
export function AdminList({title,rows,columns,page,pages,q,status,statuses=[],createHref}:{title:string;rows:Record<string,unknown>[];columns:AdminColumn[];page:number;pages:number;q:string;status:string;statuses?:string[];createHref?:string}){
  const href=(next:number)=>`?page=${next}&q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`;
  return <><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-bold">{title}</h1>{createHref&&<Link href={createHref} className="button-primary">Tạo mới</Link>}</div>
    <form className="mt-6 flex flex-wrap gap-3 rounded-xl border bg-white p-4"><label className="sr-only" htmlFor="q">Tìm kiếm</label><input id="q" name="q" defaultValue={q} placeholder="Tìm kiếm…" className="min-h-11 flex-1 rounded-lg border px-3"/><label className="sr-only" htmlFor="status">Trạng thái</label>{statuses.length>0&&<select id="status" name="status" defaultValue={status} className="min-h-11 rounded-lg border px-3"><option value="">Tất cả trạng thái</option>{statuses.map(x=><option key={x} value={x}>{x}</option>)}</select>}<button className="min-h-11 rounded-lg border px-4 font-semibold">Lọc</button></form>
    <div className="mt-5 overflow-x-auto rounded-xl border bg-white">{rows.length?<table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr>{columns.map(c=><th key={c.key} scope="col" className="px-4 py-3 font-semibold">{c.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)} className="border-t">{columns.map(c=><td key={c.key} className="px-4 py-3 align-top">{c.format?c.format(row[c.key],row):String(row[c.key]??'—')}</td>)}</tr>)}</tbody></table>:<div className="p-10 text-center text-slate-600">Chưa có dữ liệu phù hợp.</div>}</div>
    <nav className="mt-5 flex items-center justify-between" aria-label="Phân trang"><Link aria-disabled={page<=1} className={`rounded-lg border px-4 py-2 ${page<=1?'pointer-events-none opacity-50':''}`} href={href(page-1)}>Trang trước</Link><span className="text-sm">Trang {page}/{pages}</span><Link aria-disabled={page>=pages} className={`rounded-lg border px-4 py-2 ${page>=pages?'pointer-events-none opacity-50':''}`} href={href(page+1)}>Trang sau</Link></nav></>;
}
